---
- name: install tomcat
  yum: name={{ item }}
  with_items:
    - tomcat
    - apache-commons-dbcp
  sudo: yes

- name: copy tomcat server configuration
  copy: src=server.xml dest=/usr/share/tomcat/conf/server.xml owner=tomcat group=tomcat
  sudo: yes
  notify: restart tomcat

- name: copy insecure SSL key
  copy: src=keystore dest=/etc/tomcat/keystore owner=tomcat group=tomcat
  sudo: yes
  notify: restart tomcat

- name: template tomcat root application configuration
  template: src=ROOT.xml dest=/usr/share/tomcat/conf/Catalina/localhost/ROOT.xml owner=tomcat group=tomcat
  sudo: yes
  notify: restart tomcat

- name: enable tomcat
  service: name=tomcat state=started enabled=yes
  sudo: yes

- name: download postgresql jdbc driver
  get_url: url=http://jdbc.postgresql.org/download/postgresql-9.3-1102.jdbc41.jar dest=/usr/share/tomcat/lib/ owner=root group=root
  sudo: yes
  notify: restart tomcat

- name: redirect HTTP/HTTPS to tomcat
  firewalld: rich_rule='rule family="ipv4" forward-port port="{{ item.src }}" protocol="tcp" to-port="{{ item.dest }}"' permanent=true state=enabled
  with_items:
    - { src: 80, dest: 8080 }
    - { src: 443, dest: 8443 }
  sudo: yes
  notify: reload firewall

- name: open HTTP ports
  firewalld: port={{ item }} permanent=true state=enabled
  with_items:
    - 80/tcp
    - 443/tcp
  sudo: yes
  notify: reload firewall
